# Generated by Django 3.0.7 on 2020-07-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('height', models.TextField(default='')),
                ('age', models.DateField()),
                ('notes', models.TextField(default='')),
            ],
        ),
    ]
